---
title: "Project2"
output: html_document
date: "2024-03-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE,echo = TRUE, message = FALSE)
source("MCMC_sampling.R")
source("Data_processing.R")
source("PLP_model.R")
```


```{r}
library(readxl)
library(dplyr)
library(ggplot2)
```

```{r}

excel_file <- "Precip_v1.xls"  

df = data_preprocessing(excel_file, "Almaty")

ggplot(df, aes(x = Years, y = Average)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Average") +
  ggtitle("Average Precipitation Over the Years")

threshold <- get_threshold(df)

period_numbers_above_mean <- get_exceedances(df, threshold)

ggplot(df, aes(x = Years, y = Average)) +
  geom_line() +
  geom_point(aes(color = Average > threshold)) + # Color points conditionally
  scale_color_manual(values = c("black", "red")) + # Set colors: normal is black, exceedance is red
  geom_hline(yintercept = threshold, linetype = "dashed", color = "blue") + # Add threshold line
  labs(x = "Year", y = "Average Precipitation (mm)") +
  ggtitle("Average Precipitation Over the Years in Almaty")

```

```{r}
T <- get_observation_period(df)

set.seed(403-560)
samples <- mcmc_sampling(period_numbers_above_mean, T, 200000, 11000)

theta = display_statistics(samples)
theta
```


```{r}

alpha <- theta[1] 
sigma <- theta[2] 

t_values <- seq(1, T, by = 1)

# Calculate lambda(t) and m(t) for each t
lambda_values <- lambda(t_values, alpha, sigma)
m_t_values <- m_t(t_values, alpha, sigma)

sim_df <- data.frame(t = t_values, Lambda = lambda_values, M_t = m_t_values) #cumsum(lambda_values))

exceedances_df<-get_exceedance_cumsum(df, threshold)
  
  # Plot for cumulative number of exceedance cases
ggplot() +
  geom_line(data = exceedances_df, aes(x = YearInterval, y = CumulativeCases), color = "blue") +
  geom_point(data = exceedances_df, aes(x = YearInterval, y = CumulativeCases), color = "blue", size = 2) +
  # Plot for cumulative mean value function
  geom_line(data = sim_df, aes(x = t, y = M_t), color = "red") +
  labs(x = "Year", y = "Cumulative Number of Exceedance Cases / Rate Function",
       title = "Cumulative Number of Exceedance Cases") +
  theme_minimal() +
  scale_y_continuous(name = "Cumulative Number of Exceedance Cases", labels = NULL) 

ggplot(sim_df, aes(x = t, y = Lambda)) +
  geom_line(color = "green") +
  labs(x = "Time", y = "Lambda Values", title = "Lambda Values Over Time") +
  theme_minimal()

```



```{r}

excel_file <- "Tmax.xlsx"  

df = data_preprocessing(excel_file, "Almaty")

ggplot(df, aes(x = Years, y = Average)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Average") +
  ggtitle("Average Precipitation Over the Years")

threshold <- get_threshold(df)

period_numbers_above_mean <- get_exceedances(df, threshold)
```


```{r}

T <- get_observation_period(df)

set.seed(403-560)

samples <- mcmc_sampling(period_numbers_above_mean, T, 200000, 11000)


theta = display_statistics(samples)
theta
```

```{r}
alpha <- theta[1] 
sigma <- theta[2] 

t_values <- seq(1, T, by = 1)

# Calculate lambda(t) and m(t) for each t
lambda_values <- lambda(t_values, alpha, sigma)
m_t_values <- m_t(t_values, alpha, sigma)

sim_df <- data.frame(t = t_values, Lambda = lambda_values, M_t = m_t_values) #cumsum(lambda_values))

exceedances_df<-get_exceedance_cumsum(df, threshold)
  
  # Plot for cumulative number of exceedance cases
ggplot() +
  geom_line(data = exceedances_df, aes(x = YearInterval, y = CumulativeCases), color = "blue") +
  geom_point(data = exceedances_df, aes(x = YearInterval, y = CumulativeCases), color = "blue", size = 2) +
  # Plot for cumulative mean value function
  geom_line(data = sim_df, aes(x = t, y = M_t), color = "red") +
  labs(x = "Year", y = "Cumulative Number of Exceedance Cases / Rate Function",
       title = "Cumulative Number of Exceedance Cases") +
  theme_minimal() +
  scale_y_continuous(name = "Cumulative Number of Exceedance Cases", labels = NULL) 

ggplot(sim_df, aes(x = t, y = Lambda)) +
  geom_line(color = "green") +
  labs(x = "Time", y = "Lambda Values", title = "Lambda Values Over Time") +
  theme_minimal()

```


```{r}
excel_file <- "Tmax.xlsx"  

df = data_preprocessing(excel_file, "Tashkent")

ggplot(df, aes(x = Years, y = Average)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Average") +
  ggtitle("Uzbekistan Average Maximum Temperature Over the Years")

threshold <- get_threshold(df)

period_numbers_above_mean <- get_exceedances(df, threshold)

ggplot(df, aes(x = Years, y = Average)) +
  geom_line() +
  geom_point(aes(color = Average > threshold)) + # Color points conditionally
  scale_color_manual(values = c("black", "red")) + # Set colors: normal is black, exceedance is red
  geom_hline(yintercept = threshold, linetype = "dashed", color = "blue") + # Add threshold line
  labs(x = "Year", y = "Average Precipitation (mm)") +
  ggtitle("Average Precipitation Over the Years in Almaty")

```

```{r}
T <- get_observation_period(df)

set.seed(403-560)
samples <- mcmc_sampling(period_numbers_above_mean, T, 200000, 11000)

theta = display_statistics(samples)
theta
```

```{r}
alpha <- theta[1] 
sigma <- theta[2] 

t_values <- seq(1, T, by = 1)

# Calculate lambda(t) and m(t) for each t
lambda_values <- lambda(t_values, alpha, sigma)
m_t_values <- m_t(t_values, alpha, sigma)

sim_df <- data.frame(t = t_values, Lambda = lambda_values, M_t = m_t_values) #cumsum(lambda_values))

exceedances_df<-get_exceedance_cumsum(df, threshold)
  
  # Plot for cumulative number of exceedance cases
ggplot() +
  geom_line(data = exceedances_df, aes(x = YearInterval, y = CumulativeCases), color = "blue") +
  geom_point(data = exceedances_df, aes(x = YearInterval, y = CumulativeCases), color = "blue", size = 2) +
  # Plot for cumulative mean value function
  geom_line(data = sim_df, aes(x = t, y = M_t), color = "red") +
  labs(x = "Year", y = "Cumulative Number of Exceedance Cases / Rate Function",
       title = "Cumulative Number of Exceedance Cases") +
  theme_minimal() +
  scale_y_continuous(name = "Cumulative Number of Exceedance Cases", labels = NULL) 

ggplot(sim_df, aes(x = t, y = Lambda)) +
  geom_line(color = "green") +
  labs(x = "Time", y = "Lambda Values", title = "Lambda Values Over Time") +
  theme_minimal()

```



```{r}

excel_file_path <- "USA_Tever.xlsx"
data <- read_excel(excel_file_path)
data <- t(data)
years <- 1895:(1895 + length(data) - 1)
df <- data.frame(Years = years, Average = data)
df$YearInterval <- df$Years - min(df$Years)+1
rownames(df) <- NULL

ggplot(df, aes(x = Years, y = Average)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Average") +
  ggtitle("Average Precipitation Over the Years")

threshold <- get_threshold(df)

period_numbers_above_mean <- get_exceedances(df, threshold)

```


```{r}
T <- get_observation_period(df)

set.seed(403-560)
samples <- mcmc_sampling(period_numbers_above_mean, T, 200000, 11000)

theta = display_statistics(samples)
theta

```


```{r}
alpha <- theta[1] 
sigma <- theta[2] 

t_values <- seq(1, T, by = 1)

# Calculate lambda(t) and m(t) for each t
lambda_values <- lambda(t_values, alpha, sigma)
m_t_values <- m_t(t_values, alpha, sigma)

sim_df <- data.frame(t = t_values, Lambda = lambda_values, M_t = m_t_values) #cumsum(lambda_values))

exceedances_df<-get_exceedance_cumsum(df, threshold)
  
  # Plot for cumulative number of exceedance cases
ggplot() +
  geom_line(data = exceedances_df, aes(x = YearInterval, y = CumulativeCases), color = "blue") +
  geom_point(data = exceedances_df, aes(x = YearInterval, y = CumulativeCases), color = "blue", size = 2) +
  # Plot for cumulative mean value function
  geom_line(data = sim_df, aes(x = t, y = M_t), color = "red") +
  labs(x = "Year", y = "Cumulative Number of Exceedance Cases / Rate Function",
       title = "Cumulative Number of Exceedance Cases") +
  theme_minimal() +
  scale_y_continuous(name = "Cumulative Number of Exceedance Cases", labels = NULL) 

ggplot(sim_df, aes(x = t, y = Lambda)) +
  geom_line(color = "green") +
  labs(x = "Time", y = "Lambda Values", title = "Lambda Values Over Time") +
  theme_minimal()

```

```{r}
excel_file <- "Ukraine_temp.xlsx"  
  data <- read_excel(excel_file)

  # Replace -999.0 with NA and handle comma as decimal separator
  data_cleaned <- data %>%
    mutate(across(I:XII, ~ ifelse(. == -999.0, NA, .))) %>%
    mutate(across(I:XII, ~ gsub(",", ".", .))) %>%
    mutate(across(I:XII, ~ as.numeric(.)))
  
  
  # Sort data
  sorted_data <- arrange(data_cleaned, Years)
  
  # Calculate average, handling rows where all values are NA
  sorted_data$Average <- apply(sorted_data[, c("I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII")], 1, function(x) {
    if(all(is.na(x))) { 
      return(NA) 
    } else { 
      return(mean(x, na.rm = TRUE))
    }
  })
  

  # Select and adjust years
  df <- select(sorted_data, Years, Average)
  df$YearInterval <- df$Years - min(df$Years) + 1
  
ggplot(df, aes(x = Years, y = Average)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Average") +
  ggtitle("Ukraine Average Temperature Over the Years")

threshold <- get_threshold(df)

period_numbers_above_mean <- get_exceedances(df, threshold)

```

```{r}
T <- get_observation_period(df)

set.seed(403-560)
sigma_prior <- function() runif(1, 0, 40)
samples <- mcmc_sampling(period_numbers_above_mean, T, 200000, 11000)

theta = display_statistics(samples)
theta
```

```{r}
alpha <- theta[1] 
sigma <- theta[2] 

t_values <- seq(1, T, by = 1)

# Calculate lambda(t) and m(t) for each t
lambda_values <- lambda(t_values, alpha, sigma)
m_t_values <- m_t(t_values, alpha, sigma)

sim_df <- data.frame(t = t_values, Lambda = lambda_values, M_t = m_t_values) #cumsum(lambda_values))

exceedances_df<-get_exceedance_cumsum(df, threshold)
  
  # Plot for cumulative number of exceedance cases
ggplot() +
  geom_line(data = exceedances_df, aes(x = YearInterval, y = CumulativeCases), color = "blue") +
  geom_point(data = exceedances_df, aes(x = YearInterval, y = CumulativeCases), color = "blue", size = 2) +
  # Plot for cumulative mean value function
  geom_line(data = sim_df, aes(x = t, y = M_t), color = "red") +
  labs(x = "Year", y = "Cumulative Number of Exceedance Cases / Rate Function",
       title = "Cumulative Number of Exceedance Cases") +
  theme_minimal() +
  scale_y_continuous(name = "Cumulative Number of Exceedance Cases", labels = NULL) 

ggplot(sim_df, aes(x = t, y = Lambda)) +
  geom_line(color = "green") +
  labs(x = "Time", y = "Lambda Values", title = "Lambda Values Over Time") +
  theme_minimal()
```
